### PR TITLE
Add `bincount2D` and bump version

### PR DESCRIPTION
**Pull request by chris-langfield**
Moving `bincount2D` from `brainbox` to `iblutil`. https://github.com/int-brain-lab/ibl-neuropixel/pull/13

### CODE REVIEW

**Comment by chris-langfield** [comment]
Also includes some `black` reformatting

**Comment by k1o0** [comment]
Looks good but please make this a minor release instead of a patch, and update the changelog.

**Review by k1o0 — CHANGES_REQUESTED** [review]
I'd make this a minor release instead of a patch.  Other than that, just update the change log. Thanks!

**Comment by k1o0** [comment]
Hmm looks like Olivier forgot to update the change log when he merged his branch (https://github.com/int-brain-lab/iblutil/commit/727dc23c9ff2e3e8a3ebc44c510a6b2f37cb26e2).  I'll update it now then you can merge.

**Review by k1o0 — APPROVED** [review]

**Comment by chris-langfield** [comment]
Thanks!

**Pull request merged**
